"""Banco fijo de preguntas del instrumento de entrevista MVP."""

QUESTIONS: list[dict] = [
    {
        "id": "q01",
        "lente": "actores",
        "texto": "¿Quién crees que toma las decisiones más importantes en esta organización? No tiene que ser la persona con el cargo más alto.",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q02",
        "lente": "actores",
        "texto": "¿Qué tan accesible es la dirección para resolver problemas operativos del día a día? (1=Nada accesible, 5=Muy accesible)",
        "tipo": "escala_5",
        "opciones": [],
    },
    {
        "id": "q03",
        "lente": "actores",
        "texto": "¿Hay alguien cuya aprobación o visto bueno es necesario para que las cosas avancen, aunque no sea su responsabilidad formal?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q04",
        "lente": "procesos",
        "texto": "Describe un proceso de tu trabajo diario que sientes que podría ser más rápido o más simple. ¿Dónde se detiene o complica?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q05",
        "lente": "procesos",
        "texto": "¿Con qué frecuencia tienes que esperar a otra persona o área para poder avanzar en tu trabajo? (1=Casi nunca, 5=Casi siempre)",
        "tipo": "escala_5",
        "opciones": [],
    },
    {
        "id": "q06",
        "lente": "procesos",
        "texto": "¿Cuándo fue la última vez que un proceso no funcionó como se esperaba? ¿Qué pasó?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q07",
        "lente": "reglas",
        "texto": "¿Hay reglas o procedimientos formales que en la práctica nadie sigue? ¿Por qué crees que es así?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q08",
        "lente": "reglas",
        "texto": "¿Hay cosas que 'todos saben que se hacen así' aunque no estén escritas en ningún lado? ¿Cuál es la más importante?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q09",
        "lente": "reglas",
        "texto": "¿Qué tan claras son las reglas sobre quién puede tomar qué decisiones? (1=Muy confusas, 5=Muy claras)",
        "tipo": "escala_5",
        "opciones": [],
    },
    {
        "id": "q10",
        "lente": "incentivos",
        "texto": "¿Qué comportamientos o resultados son los que realmente se reconocen o recompensan aquí, aunque no sean los declarados oficialmente?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q11",
        "lente": "incentivos",
        "texto": "¿Hay situaciones en las que hacer lo correcto para la organización va en contra de lo que te conviene a ti personalmente? ¿Puedes dar un ejemplo?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q12",
        "lente": "incentivos",
        "texto": "¿Sientes que tu esfuerzo y contribución se reconocen de forma justa? (1=Para nada, 5=Completamente)",
        "tipo": "escala_5",
        "opciones": [],
    },
    {
        "id": "q13",
        "lente": "episodios",
        "texto": "Describe una situación reciente (últimos 6 meses) en la que algo salió bien gracias a cómo está organizado el trabajo aquí.",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q14",
        "lente": "episodios",
        "texto": "Describe una situación reciente en la que algo salió mal o generó fricción innecesaria. ¿Qué lo causó?",
        "tipo": "abierta",
        "opciones": [],
    },
    {
        "id": "q15",
        "lente": "episodios",
        "texto": "Si pudieras cambiar una sola cosa de cómo funciona esta organización, ¿qué cambiarías y por qué?",
        "tipo": "abierta",
        "opciones": [],
    },
]

__all__ = ["QUESTIONS"]
